"""Recommendation engine — data-driven from the question rows.

For every "No" answer, produce a 5-field per-gap recommendation:
  Gap / Capability status / Recommended action / Recommended learning /
  Potential service.

The recommendation content is **read from the question row**, not
generated by an LLM. The LLM layer may rephrase but never alter
substance or priority.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.models.framework import Question


@dataclass(frozen=True)
class Recommendation:
    """One per gap surfaced in an assessment."""

    question_id: str
    pillar_id: int
    capability_id: str
    gap: str
    capability_status: str
    recommended_action: str
    recommended_learning: str
    potential_service: str
    priority: str
    why_it_matters: str | None = None


def build_recommendations(
    answers: dict[str, str],
    questions: dict[str, Question],
    capability_status: dict[str, str],
) -> list[Recommendation]:
    """Build the per-gap recommendation list from the answered "No"s.

    Args:
        answers: ``{question_id: 'yes'|'no'}``
        questions: ``{question_id: Question}`` lookup (just the answered ones)
        capability_status: ``{capability_id: status_string}`` from the scorer

    Returns:
        List of Recommendation, ordered Quick Wins first, then Medium Term,
        then Strategic. Within each priority bucket, the original
        question order is preserved.
    """
    recs: list[Recommendation] = []
    for qid, answer in answers.items():
        if answer != "no":
            continue
        q = questions.get(qid)
        if q is None:
            continue
        recs.append(
            Recommendation(
                question_id=qid,
                pillar_id=q.pillar_id,
                capability_id=q.capability_id,
                gap=q.question_text,
                capability_status=capability_status.get(q.capability_id, "non_existent"),
                recommended_action=q.if_no_recommendation or "Review this capability.",
                recommended_learning=", ".join(q.support_available) or "Future Farms Advisory",
                potential_service=q.service_ref or "Farm business advisory",
                priority=q.priority,
                why_it_matters=q.why_it_matters,
            )
        )

    priority_order = {"quick_win": 0, "medium_term": 1, "strategic": 2}
    recs.sort(key=lambda r: (priority_order.get(r.priority, 99), r.question_id))
    return recs


def strongest_and_priority_pillars(
    pillar_scores: dict[int, float],
) -> tuple[int | None, int | None]:
    """Return (strongest_pillar_id, priority_gap_pillar_id) by score."""
    if not pillar_scores:
        return None, None
    sorted_pillars = sorted(pillar_scores.items(), key=lambda kv: kv[1], reverse=True)
    return sorted_pillars[0][0], sorted_pillars[-1][0]
